@baseUrl = http://localhost:3000/api
@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTY3ZGMxNDlhNjljZjAxYzc2Y2ZkZTAiLCJkaXNwbGF5TmFtZSI6IkJyeWFuIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY4NDE0NjMyLCJleHAiOjE3Njg0MTgyMzJ9.MrzrjOJZXTvC8M2FDIRMVf8sAmJCGlQQA6hULxNIB1w


### Colección /REGISTER - /LOGIN

### /REGISTER
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "displayName": "Bryan Admin",
  "email": "admin@example.com",
  "password": "qwerty2",
  "role": "admin"
}

### /LOGIN

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "email@example.com",
  "password": "qwerty1"
}

#----------------------------------------------

### Colección /PRODUCTS

### Petición GET
GET {{baseUrl}}/products

### Petición GET by Id
GET {{baseUrl}}/products/6967de519a69cf01c76cfde8

### Petición POST
POST  {{baseUrl}}/products
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
  "name": "Espresso",
  "price": 3.50,
  "stock": 100
}

### Petición PUT
PUT {{baseUrl}}/products/6967de519a69cf01c76cfde8
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
  "name": "Capuchino",
  "price": 40,
  "stock": 150
}

### Petición DELETE
DELETE {{baseUrl}}/products/6967dfb29a69cf01c76cfdf9
Authorization: Bearer {{tokenAdmin}}

#----------------------------------------------

### Colección /CUSTOMERS

### Petición GET
GET {{baseUrl}}/customers

### Petición POST
POST  {{baseUrl}}/customers

### Petición GET/:id
GET {{baseUrl}}/customers/6966ae6cf5bafa00cfcab09c

#----------------------------------------------

### Colección /SALES

### Petición POST
POST  {{baseUrl}}/sales

### Petición GET/:id
GET {{baseUrl}}/sales/




  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTY3ZGMxNDlhNjljZjAxYzc2Y2ZkZTAiLCJkaXNwbGF5TmFtZSI6IkJyeWFuIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY4NDE0NjMyLCJleHAiOjE3Njg0MTgyMzJ9.MrzrjOJZXTvC8M2FDIRMVf8sAmJCGlQQA6hULxNIB1w",

  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTY3ZGMxNDlhNjljZjAxYzc2Y2ZkZTAiLCJpYXQiOjE3Njg0MTQ2MzIsImV4cCI6MTc2OTAxOTQzMn0.vjQfdMIpdXZzcZtREUydnMDJUFjgZSye7esFoTE_2Cg"